### ISSUE TITLE
small suggestion

### ISSUE THREAD

**Issue by rcrooks** [mdoyleaz/vs-code-theme-minimal_green#1]
@mdoyleaz I really like this theme. There is one small change I'd like to recommend: make the punctuation/brackets (e.g. html tag brackets) color a little different than the tag names. If you are open to pull requests, I'd be happy to give it a try.
Best,
Robert

**Comment by mdoyleaz** [comment]
@rcrooks Yeah, create the PR and I will check it out and merge it in.

**Comment by mdoyleaz** [comment]
@rcrooks Thank you for taking the time to push your request!

I've gone ahead and merged your PR and published the changes.

Feel free to make any more changes that you see fit!

**Comment by rcrooks** [comment]
@mdoyleaz thank you for taking the suggestion - and your tweak made it even better! Just shared with the rest of my dev team :) 

Feels just right for an early spring theme.
